edition = "2021"
style_edition = "2021"
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
merge_derives = true
match_arm_leading_pipes = "Never"
print_misformatted_file_names = true
